//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.WPF.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected, charging....
        /// </summary>
        public static string ACAdapterConnectedAndCharging {
            get {
                return ResourceManager.GetString("ACAdapterConnectedAndCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected, not charging.
        /// </summary>
        public static string ACAdapterConnectedNotCharging {
            get {
                return ResourceManager.GetString("ACAdapterConnectedNotCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the accent color of the app..
        /// </summary>
        public static string AccentColor_Description {
            get {
                return ResourceManager.GetString("AccentColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string AccentColor_Title {
            get {
                return ResourceManager.GetString("AccentColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Actions defined. Click &quot;Add new&quot; to create new Action..
        /// </summary>
        public static string Actions_Empty {
            get {
                return ResourceManager.GetString("Actions_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled these action will run automatically. Whenever state changes, all actions will be evaluated from top to bottom.
        ///Only actions that match current state will run..
        /// </summary>
        public static string Actions_Message {
            get {
                return ResourceManager.GetString("Actions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions_Title {
            get {
                return ResourceManager.GetString("Actions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenovo Legion Toolkit must be running for automatic actions to work..
        /// </summary>
        public static string ActionsEnable_Message {
            get {
                return ResourceManager.GetString("ActionsEnable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string ActionsEnabled_Title {
            get {
                return ResourceManager.GetString("ActionsEnabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change options below unless you really know what you are doing..
        /// </summary>
        public static string Advanced_Message {
            get {
                return ResourceManager.GetString("Advanced_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced_Title {
            get {
                return ResourceManager.GetString("Advanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenovo Legion Toolkit.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation_Title {
            get {
                return ResourceManager.GetString("Automation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized to tray when you log in to Windows.
        ///Startup is delayed by 30 seconds for compatibility reasons..
        /// </summary>
        public static string Autorun_Message {
            get {
                return ResourceManager.GetString("Autorun_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorun.
        /// </summary>
        public static string Autorun_Title {
            get {
                return ResourceManager.GetString("Autorun_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Battery_Title {
            get {
                return ResourceManager.GetString("Battery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current temperature of the battery..
        /// </summary>
        public static string BatteryTemperature_Message {
            get {
                return ResourceManager.GetString("BatteryTemperature_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery temperature.
        /// </summary>
        public static string BatteryTemperature_Title {
            get {
                return ResourceManager.GetString("BatteryTemperature_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build: .
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Boost Modes.
        /// </summary>
        public static string CPUBoostModes {
            get {
                return ResourceManager.GetString("CPUBoostModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current battery capacity..
        /// </summary>
        public static string CurrentCapacity_Message {
            get {
                return ResourceManager.GetString("CurrentCapacity_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current capacity.
        /// </summary>
        public static string CurrentCapacity_Title {
            get {
                return ResourceManager.GetString("CurrentCapacity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of charge/discharge cycles..
        /// </summary>
        public static string CycleCount_Message {
            get {
                return ResourceManager.GetString("CycleCount_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle count.
        /// </summary>
        public static string CycleCount_Title {
            get {
                return ResourceManager.GetString("CycleCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery capacity as designed..
        /// </summary>
        public static string DesignCapacity_Message {
            get {
                return ResourceManager.GetString("DesignCapacity_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design capacity.
        /// </summary>
        public static string DesignCapacity_Title {
            get {
                return ResourceManager.GetString("DesignCapacity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Legion Zone and it&apos;s service without uninstalling it.
        ///Restart is recommended after changing this option..
        /// </summary>
        public static string DisableLegionZone_Message {
            get {
                return ResourceManager.GetString("DisableLegionZone_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Legion Zone.
        /// </summary>
        public static string DisableLegionZone_Title {
            get {
                return ResourceManager.GetString("DisableLegionZone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Lenovo Hotkeys and it&apos;s service without uninstalling it.
        ///If disabled, this app will handle Fn shortcuts
        ///Restart is recommended after changing this option..
        /// </summary>
        public static string DisableLenovoHotkeys_Message {
            get {
                return ResourceManager.GetString("DisableLenovoHotkeys_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Lenovo Hotkeys.
        /// </summary>
        public static string DisableLenovoHotkeys_Title {
            get {
                return ResourceManager.GetString("DisableLenovoHotkeys_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Lenovo Vantage and it&apos;s service without uninstalling it.
        ///Restart is recommended after changing this option..
        /// </summary>
        public static string DisableVantage_Message {
            get {
                return ResourceManager.GetString("DisableVantage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Lenovo Vantage.
        /// </summary>
        public static string DisableVantage_Title {
            get {
                return ResourceManager.GetString("DisableVantage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate at which battery is charged (+), or discharged (-)..
        /// </summary>
        public static string DischargeRate_Message {
            get {
                return ResourceManager.GetString("DischargeRate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge rate.
        /// </summary>
        public static string DischargeRate_Title {
            get {
                return ResourceManager.GetString("DischargeRate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development and maintenance of Lenovo Legion Toolkit takes a lot of time. If you like using this software you can support it&apos;s future by donating an amount of your choice.
        ///
        ///Click the PayPal logo below or scan the QR code to donate with PayPal.
        ///
        ///Thanks in advance!.
        /// </summary>
        public static string Donate_Message {
            get {
                return ResourceManager.GetString("Donate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate_Title {
            get {
                return ResourceManager.GetString("Donate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables notification for Fn keys actions like microphone mute
        ///Enable this option if you have conflicts with full screen applications..
        /// </summary>
        public static string DontShowNotifications_Message {
            get {
                return ResourceManager.GetString("DontShowNotifications_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show notifications.
        /// </summary>
        public static string DontShowNotifications_Title {
            get {
                return ResourceManager.GetString("DontShowNotifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time remaining: {0}.
        /// </summary>
        public static string EstimatedBatteryLifeRemaining {
            get {
                return ResourceManager.GetString("EstimatedBatteryLifeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating time....
        /// </summary>
        public static string EstimatingBatteryLife {
            get {
                return ResourceManager.GetString("EstimatingBatteryLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can exclude refresh rates, to make Fn+R shortcut more useful..
        /// </summary>
        public static string ExcludeRefreshRates_Message {
            get {
                return ResourceManager.GetString("ExcludeRefreshRates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Refresh Rates.
        /// </summary>
        public static string ExcludeRefreshRates_Title {
            get {
                return ResourceManager.GetString("ExcludeRefreshRates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When was the battery first used..
        /// </summary>
        public static string FirstUse_Message {
            get {
                return ResourceManager.GetString("FirstUse_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First use date.
        /// </summary>
        public static string FirstUseDate_Title {
            get {
                return ResourceManager.GetString("FirstUseDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery capacity when fully charged..
        /// </summary>
        public static string FullChargeCapacity_Message {
            get {
                return ResourceManager.GetString("FullChargeCapacity_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full charge capacity.
        /// </summary>
        public static string FullChargeCapacity_Title {
            get {
                return ResourceManager.GetString("FullChargeCapacity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphics_Title {
            get {
                return ResourceManager.GetString("Graphics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is not compatible with Lenovo Legion Toolkit..
        /// </summary>
        public static string IncompatibleDevice_Message {
            get {
                return ResourceManager.GetString("IncompatibleDevice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenovo Legion Toolkit.
        /// </summary>
        public static string IncompatibleDevice_Title {
            get {
                return ResourceManager.GetString("IncompatibleDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Backlight.
        /// </summary>
        public static string KeyboardBacklight_Title {
            get {
                return ResourceManager.GetString("KeyboardBacklight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest release on GitHub.
        /// </summary>
        public static string LatestReleaseOnGitHub {
            get {
                return ResourceManager.GetString("LatestReleaseOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low wattage charger connected.
        /// </summary>
        public static string LowWattageChargerConnected {
            get {
                return ResourceManager.GetString("LowWattageChargerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When was the battery manufactured..
        /// </summary>
        public static string ManufactureDate_Message {
            get {
                return ResourceManager.GetString("ManufactureDate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture date.
        /// </summary>
        public static string ManufactureDate_Title {
            get {
                return ResourceManager.GetString("ManufactureDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always minimize to tray. Close with right click on tray icon..
        /// </summary>
        public static string MinimizeOnClose_Message {
            get {
                return ResourceManager.GetString("MinimizeOnClose_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on close.
        /// </summary>
        public static string MinimizeOnClose_Title {
            get {
                return ResourceManager.GetString("MinimizeOnClose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible keyboards found.
        /// </summary>
        public static string NoCompatibleKeyboardsFound {
            get {
                return ResourceManager.GetString("NoCompatibleKeyboardsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time since laptop was last connected to AC power.&amp;#x0a;This time might not be accurate if laptop was charged when sleeping or off..
        /// </summary>
        public static string OnBatterySince_Message {
            get {
                return ResourceManager.GetString("OnBatterySince_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On battery since.
        /// </summary>
        public static string OnBatterySince_Title {
            get {
                return ResourceManager.GetString("OnBatterySince_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other_Title {
            get {
                return ResourceManager.GetString("Other_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power_Title {
            get {
                return ResourceManager.GetString("Power_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plans.
        /// </summary>
        public static string PowerPlans {
            get {
                return ResourceManager.GetString("PowerPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project website on GitHub.
        /// </summary>
        public static string ProjectWebsiteOnGitHub {
            get {
                return ResourceManager.GetString("ProjectWebsiteOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Quick Actions defined. Click &quot;Add new&quot; to create new Quick Action..
        /// </summary>
        public static string QuickActions_Empty {
            get {
                return ResourceManager.GetString("QuickActions_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick actions are available in the right click menu of the tray icon..
        /// </summary>
        public static string QuickActions_Message {
            get {
                return ResourceManager.GetString("QuickActions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        public static string QuickActions_Title {
            get {
                return ResourceManager.GetString("QuickActions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set light theme, dark theme or follow system settings..
        /// </summary>
        public static string Theme_Description {
            get {
                return ResourceManager.GetString("Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme_Title {
            get {
                return ResourceManager.GetString("Theme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd party libraries.
        /// </summary>
        public static string ThirdPartyLibraries {
            get {
                return ResourceManager.GetString("ThirdPartyLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception occurred:
        ///{0}
        ///
        ///Please report the issue on {1}..
        /// </summary>
        public static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} available!.
        /// </summary>
        public static string UpdateAvailableWithVersion {
            get {
                return ResourceManager.GetString("UpdateAvailableWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
