name: Feature Request
description: Suggest an idea for this project
title: "[FEAT]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request. Please provide as much information as possible.
  - type: input
    id: version
    attributes:
      label: Version
      description: Which Lenovo Legion Toolkit version do you use?
      placeholder: e.g. 2.5.1
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: Which operating system do you use?
      placeholder: e.g. Windows 11 21H2 build 22000
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: Which laptop do you use?
      placeholder: e.g. Legion 5 Pro 16ACH6
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Type here...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: How would you like the problem to be solved?
      description: A clear and concise description of what you would like to happen.
      placeholder: Type here...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Type here...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: If applicable, add screenshots or other relevant information to help explain your problem.
