//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Lib.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string AlwaysOnUSBState_Off {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On, always.
        /// </summary>
        public static string AlwaysOnUSBState_OnAlways {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On, when sleeping.
        /// </summary>
        public static string AlwaysOnUSBState_OnWhenSleeping {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnWhenSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservation.
        /// </summary>
        public static string BatteryState_Conservation {
            get {
                return ResourceManager.GetString("BatteryState_Conservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string BatteryState_Normal {
            get {
                return ResourceManager.GetString("BatteryState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Charge.
        /// </summary>
        public static string BatteryState_RapidCharge {
            get {
                return ResourceManager.GetString("BatteryState_RapidCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered Off.
        /// </summary>
        public static string GPUController_PoweredOff {
            get {
                return ResourceManager.GetString("GPUController_PoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered On.
        /// </summary>
        public static string GPUController_PoweredOn {
            get {
                return ResourceManager.GetString("GPUController_PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dGPU.
        /// </summary>
        public static string HybridModeState_Off {
            get {
                return ResourceManager.GetString("HybridModeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string HybridModeState_On {
            get {
                return ResourceManager.GetString("HybridModeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid-Auto.
        /// </summary>
        public static string HybridModeState_OnAuto {
            get {
                return ResourceManager.GetString("HybridModeState_OnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid-iGPU.
        /// </summary>
        public static string HybridModeState_OnIGPUOnly {
            get {
                return ResourceManager.GetString("HybridModeState_OnIGPUOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string PowerModeState_Balance {
            get {
                return ResourceManager.GetString("PowerModeState_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string PowerModeState_GodMode {
            get {
                return ResourceManager.GetString("PowerModeState_GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string PowerModeState_Performance {
            get {
                return ResourceManager.GetString("PowerModeState_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        public static string PowerModeState_Quiet {
            get {
                return ResourceManager.GetString("PowerModeState_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string RBGKeyboardSpeed_Fast {
            get {
                return ResourceManager.GetString("RBGKeyboardSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        public static string RBGKeyboardSpeed_Fastest {
            get {
                return ResourceManager.GetString("RBGKeyboardSpeed_Fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string RBGKeyboardSpeed_Slow {
            get {
                return ResourceManager.GetString("RBGKeyboardSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowest.
        /// </summary>
        public static string RBGKeyboardSpeed_Slowest {
            get {
                return ResourceManager.GetString("RBGKeyboardSpeed_Slowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Off {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 1.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_One {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 3.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Three {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 2.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Two {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string RGBKeyboardBrightness_High {
            get {
                return ResourceManager.GetString("RGBKeyboardBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string RGBKeyboardBrightness_Low {
            get {
                return ResourceManager.GetString("RGBKeyboardBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath.
        /// </summary>
        public static string RGBKeyboardEffect_Breath {
            get {
                return ResourceManager.GetString("RGBKeyboardEffect_Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        public static string RGBKeyboardEffect_Smooth {
            get {
                return ResourceManager.GetString("RGBKeyboardEffect_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string RGBKeyboardEffect_Static {
            get {
                return ResourceManager.GetString("RGBKeyboardEffect_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Left.
        /// </summary>
        public static string RGBKeyboardEffect_WaveLTR {
            get {
                return ResourceManager.GetString("RGBKeyboardEffect_WaveLTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Right.
        /// </summary>
        public static string RGBKeyboardEffect_WaveRTL {
            get {
                return ResourceManager.GetString("RGBKeyboardEffect_WaveRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string WhiteKeyboardBacklightState_High {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string WhiteKeyboardBacklightState_Low {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string WhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
    }
}
